### ISSUE TITLE
TS: Error in type declaration

### ISSUE THREAD

**Issue by romgere** [Zod-/jsVideoUrlParser#71]
Hi I have an issue when using the package with typescript : 

```
node_modules/js-video-url-parser/lib/index.d.ts:9:15 - error TS2307: Cannot find module './provider/template' or its corresponding type declarations.
```

It looks like the `template` files are not include in the `lib` folder of npm package : 
```
├── base.d.ts
├── base.js
├── index.d.ts
├── index.js
├── provider
│   ├── base-provider.d.ts
│   ├── canalplus.d.ts
│   ├── canalplus.js
│   ├── coub.d.ts
│   ├── coub.js
│   ├── dailymotion.d.ts
│   ├── dailymotion.js
│   ├── soundcloud.d.ts
│   ├── soundcloud.js
│   ├── teachertube.d.ts
│   ├── teachertube.js
│   ├── ted.d.ts
│   ├── ted.js
│   ├── tiktok.d.ts
│   ├── tiktok.js
│   ├── twitch.d.ts
│   ├── twitch.js
│   ├── vimeo.d.ts
│   ├── vimeo.js
│   ├── wistia.d.ts
│   ├── wistia.js
│   ├── youku.d.ts
│   ├── youku.js
│   ├── youtube.d.ts
│   └── youtube.js
├── testUrls.js
├── urlParser.d.ts
├── urlParser.js
└── util.js
```

(:point_up: `node_modules/js-video-url-parser/lib`)

**Comment by claabs** [comment]
That's my bad. I think [this line](https://github.com/Zod-/jsVideoUrlParser/blob/master/lib/index.d.ts#L9) just needs to be removed. There's no reason for template to be included in the release package.

**Comment by brunolazzaro** [comment]
@claabs I created a PR for that, feel free to merge it!

**Comment by Zod-** [comment]
I just merged and pushed the fix

**Comment by romgere** [comment]
The issue still exists in last release `0.4.3`...

It seems the PR didn't fix it : 
```
node_modules/js-video-url-parser/lib/index.d.ts:9:15 - error TS2307: Cannot find module './provider/template' or its corresponding type declarations.

9 export * from './provider/template';
                ~~~~~~~~~~~~~~~~~~~~~
```

I didn't take a look to the PR before merge, but the problem does not concern this line : 
https://github.com/brunolazzaro/jsVideoUrlParser/blob/c10f242c8ae4299eb89d7ae5013b0efd91f5c37c/lib/provider/template.d.ts#L1

But the import of `template.d.ts` it self wich is not present in release package.

Following @claabs comment, do you want me to make a PR to remove the import line ?

**Comment by brunolazzaro** [comment]
@romgere Can you check by installing the package directly from the repo? `yarn add https://github.com/Zod-/jsVideoUrlParser`. 

My PR only fixed the type problem, so if you install the package directly from the repo it will work but as you said, and following @claabs it's clear that we need to delete those files entirely since they are ignored by NPM (https://github.com/Zod-/jsVideoUrlParser/blob/master/.npmignore) thus will always break on release.

**Comment by brunolazzaro** [comment]
Just opened a PR with the line removed as indicated by @claabs. This should resolve the issue with the released version through NPM.

**Comment by romgere** [comment]
> @romgere Can you check by installing the package directly from the repo? `yarn add https://github.com/Zod-/jsVideoUrlParser`

@brunolazzaro I confirm installing from GH can fixe the issue. 

But a fix for npm release have to be also release I think, Thx for tackling this :pray:

**Comment by rskvazh** [comment]
Same problem from NPM package. Broke app build.

**Comment by agalazis** [comment]
any news? Can you at least reopen?

**Comment by murraco** [comment]
Just added a PR [here](https://github.com/Zod-/jsVideoUrlParser/pull/93) to fix this issue, it would be great if you could merge it @Zod-. Thanks!

**Comment by Zod-** [comment]
Hope it's fixed now
